In [ ]:
import numpy as np

In [ ]:
# -21x + 3y = 6
# 3x - 3y = 3

In [ ]:
A = np.array([[-21, 3], [3, -3]])
b = np.array([6, 3])

In [ ]:
np.linalg.solve(A, b)

array([-0.5, -1.5])

In [ ]:
np.linalg.norm(np.array([3,5, 4,6,54,7]))

np.float64(55.235857918565905)

In [ ]:
a = np.array([3,5])
b = np.array([3,8])

In [ ]:
np.linalg.norm(a-b)

np.float64(3.0)

In [ ]:
mat = np.array([[1,2,3], [1,1,3], [2,4,6]])

In [ ]:
mat

array([[1, 2, 3],
       [1, 1, 3],
       [2, 4, 6]])

In [ ]:
mat + mat-1

array([[ 1,  3,  5],
       [ 1,  1,  5],
       [ 3,  7, 11]])

In [ ]:
mat.T

array([[1, 1, 2],
       [2, 1, 4],
       [3, 3, 6]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
mat

array([[1, 2, 3],
       [1, 1, 3],
       [2, 4, 6]])

In [ ]:
# det
np.linalg.det(mat)

np.float64(0.0)

In [ ]:
np.linalg.det(mat[1:3, 1:3])

np.float64(-6.0)

In [ ]:
mat[1:3, 1:3]

array([[1, 3],
       [4, 6]])

In [ ]:
# eigenvalues and eigenvectors
mat * 8

array([[ 8, 16, 24],
       [ 8,  8, 24],
       [16, 32, 48]])

In [ ]:
a, a*4, a + 4, a/3

(array([3, 5]),
 array([12, 20]),
 array([7, 9]),
 array([1.        , 1.66666667]))

In [ ]:
Av = lambda v

In [ ]:
value, vec=np.linalg.eig(mat)

In [ ]:
value

array([ 8.79583152e+00, -3.82849998e-16, -7.95831523e-01])

In [ ]:
vec

array([[-4.15003761e-01, -9.48683298e-01,  2.22531524e-01],
       [-3.72638418e-01, -7.49798002e-16, -8.67409134e-01],
       [-8.30007522e-01,  3.16227766e-01,  4.45063047e-01]])

In [ ]:
mat * vec

array([[-4.15003761e-01, -1.89736660e+00,  6.67594571e-01],
       [-3.72638418e-01, -7.49798002e-16, -2.60222740e+00],
       [-1.66001504e+00,  1.26491106e+00,  2.67037828e+00]])

In [ ]:
value * vec

array([[-3.65030317e+00,  3.63203399e-16, -1.77097601e-01],
       [-3.27766475e+00,  2.87060164e-31,  6.90311532e-01],
       [-7.30060633e+00, -1.21067800e-16, -3.54195203e-01]])

In [ ]:
a[:, np.newaxis].shape

(2, 1)

In [ ]:
a[np.newaxis, :].shape

(1, 2)