In [1]:
import numpy as np

In [ ]:
np.array([1,2,3,]) # 1 D
np.arange(0, 10)
np.zeros()
np.ones()

In [4]:
# (3,2) # 2D
np.linspace(0, 1, 500) # 1D size = 50

array([0.        , 0.00200401, 0.00400802, 0.00601202, 0.00801603,
       0.01002004, 0.01202405, 0.01402806, 0.01603206, 0.01803607,
       0.02004008, 0.02204409, 0.0240481 , 0.0260521 , 0.02805611,
       0.03006012, 0.03206413, 0.03406814, 0.03607214, 0.03807615,
       0.04008016, 0.04208417, 0.04408818, 0.04609218, 0.04809619,
       0.0501002 , 0.05210421, 0.05410822, 0.05611222, 0.05811623,
       0.06012024, 0.06212425, 0.06412826, 0.06613226, 0.06813627,
       0.07014028, 0.07214429, 0.0741483 , 0.0761523 , 0.07815631,
       0.08016032, 0.08216433, 0.08416834, 0.08617234, 0.08817635,
       0.09018036, 0.09218437, 0.09418838, 0.09619238, 0.09819639,
       0.1002004 , 0.10220441, 0.10420842, 0.10621242, 0.10821643,
       0.11022044, 0.11222445, 0.11422846, 0.11623246, 0.11823647,
       0.12024048, 0.12224449, 0.1242485 , 0.12625251, 0.12825651,
       0.13026052, 0.13226453, 0.13426854, 0.13627255, 0.13827655,
       0.14028056, 0.14228457, 0.14428858, 0.14629259, 0.14829

In [6]:
np.empty((2,3))

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [7]:
arr = np.arange(0, 11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros_like(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones_like(arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
arr[0]

np.int64(0)

In [15]:
arr[0:3] # slicing

array([0, 1, 2])

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
0 3 7

In [21]:
# boolean indexing

In [27]:
arr[np.array([True, False, False, True, False, False, False, True, False, True, False])]

array([0, 3, 7, 9])

In [41]:
arr[-1::-1] # reverse

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [42]:
arr.reshape()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr.size

11

In [45]:
arr = arr[1:].reshape(2,5)

In [46]:
# 2,5,
# 5,2
# 10,
# 10, 1
# 1,10

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
arr[-2, -1]

np.int64(5)

In [69]:
arr[:, 1::2]

array([[2, 4],
       [7, 9]])

In [ ]:
0 0:2
1 3:

In [70]:
arr[:, ]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
np.array([[1,1, 0,0,0], [0,0,0,1,1

array([[1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1]])

In [73]:
arr[np.array([[1,1, 0,0,0], [0,0,0,1,1]]).astype('bool')]

array([ 1,  2,  9, 10])

In [76]:
# 3D
arr = np.arange(1, 31).reshape(2,5,3)

In [82]:
arr[1, 2,1]

np.int64(23)

In [87]:
arr[:, 1:3, 1:]

array([[[ 5,  6],
        [ 8,  9]],

       [[20, 21],
        [23, 24]]])

In [85]:
arr.ndim

3

In [88]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]]])

In [100]:
arr[:, ::2, ::2]

array([[[ 1,  3],
        [ 7,  9],
        [13, 15]],

       [[16, 18],
        [22, 24],
        [28, 30]]])

In [91]:
arr[0:1, 2::2, 1::]

array([[[ 8,  9],
        [14, 15]]])

In [96]:
arr[:, 0::4, :]

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[16, 17, 18],
        [28, 29, 30]]])

In [104]:
arr.shape

(2, 5, 3)

In [105]:
arr.size

30

In [106]:
arr.ndim

3

In [107]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [109]:
a.shape, b.shape

((3,), (3,))

In [111]:
a + 3

array([4, 5, 6])

In [113]:
a - 5

array([-4, -3, -2])

In [114]:
a * 4

array([ 4,  8, 12])

In [117]:
a/3

array([0.33333333, 0.66666667, 1.        ])

In [118]:
a** 2

array([1, 4, 9])

In [119]:
a // 2

array([0, 1, 1])

In [121]:
a %2

array([1, 0, 1])

In [122]:
a > 4

array([False, False, False])

In [124]:
b < 3

array([ True,  True, False])

In [125]:
a >= 3 

array([False, False,  True])

In [126]:
a <= 2

array([ True,  True, False])

In [127]:
a != 3, a == 1

(array([ True,  True, False]), array([ True, False, False]))

In [135]:
# & and 
# | or 
# ~ not 

~ (a== 1)

array([False,  True,  True])

In [139]:
mask = (a== 0)| ~ (a== 1)

In [140]:
a[mask]

array([2, 3])