In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
np.sum(arr)

np.int64(6)

In [5]:
np.prod(arr)

np.int64(6)

In [6]:
np.add(arr, arr)

array([2, 4, 6])

In [7]:
arr + arr


array([2, 4, 6])

In [10]:
arr = np.arange(0, 6).reshape(2,3)
arr2 = np.arange(0, 6).reshape(3,2)

In [11]:
arr, arr2

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [12]:
np.multiply(arr, arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [13]:
np.matmul(arr, arr2)

array([[10, 13],
       [28, 40]])

In [14]:
arr @ arr2

array([[10, 13],
       [28, 40]])

In [17]:
np.dot(arr, arr2) * (arr@arr2)

array([[ 100,  169],
       [ 784, 1600]])

In [19]:
arr[0]

array([0, 1, 2])

In [20]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
np.add(arr[:, 0], arr[:,1])

array([1, 7])

In [24]:
arr[:, 0]

array([0, 3])

In [25]:
arr[:, 1]

array([1, 4])

In [26]:
arr.ndim

2

In [27]:
np.sum(arr, axis=0)

array([3, 5, 7])

In [28]:
np.sum(arr, axis=1)

array([ 3, 12])

In [31]:
a = np.linspace(3,5, 30).reshape(3,5,2)

In [35]:
np.sum(a, axis=2)

array([[6.06896552, 6.34482759, 6.62068966, 6.89655172, 7.17241379],
       [7.44827586, 7.72413793, 8.        , 8.27586207, 8.55172414],
       [8.82758621, 9.10344828, 9.37931034, 9.65517241, 9.93103448]])

In [36]:
a

array([[[3.        , 3.06896552],
        [3.13793103, 3.20689655],
        [3.27586207, 3.34482759],
        [3.4137931 , 3.48275862],
        [3.55172414, 3.62068966]],

       [[3.68965517, 3.75862069],
        [3.82758621, 3.89655172],
        [3.96551724, 4.03448276],
        [4.10344828, 4.17241379],
        [4.24137931, 4.31034483]],

       [[4.37931034, 4.44827586],
        [4.51724138, 4.5862069 ],
        [4.65517241, 4.72413793],
        [4.79310345, 4.86206897],
        [4.93103448, 5.        ]]])

In [40]:
np.positive(a)

array([[[3.        , 3.06896552],
        [3.13793103, 3.20689655],
        [3.27586207, 3.34482759],
        [3.4137931 , 3.48275862],
        [3.55172414, 3.62068966]],

       [[3.68965517, 3.75862069],
        [3.82758621, 3.89655172],
        [3.96551724, 4.03448276],
        [4.10344828, 4.17241379],
        [4.24137931, 4.31034483]],

       [[4.37931034, 4.44827586],
        [4.51724138, 4.5862069 ],
        [4.65517241, 4.72413793],
        [4.79310345, 4.86206897],
        [4.93103448, 5.        ]]])

In [41]:
a** a

array([[[  27.        ,   31.22925918],
        [  36.17701421,   41.97223378],
        [  48.76807468,   56.74658605],
        [  66.1243574 ,   77.15930535],
        [  90.15883438,  105.48965781]],

       [[ 123.58962517,  144.98197694],
        [ 170.29253735,  200.27046614],
        [ 235.81332436,  277.99737306],
        [ 328.11422348,  387.71520206],
        [ 458.6650923 ,  543.20728087]],

       [[ 644.04278334,  764.42617287],
        [ 908.28210718, 1080.34697339],
        [1286.34118122, 1533.17887681],
        [1829.22337451, 2184.59847887],
        [2611.56817461, 3125.        ]]])

In [43]:
np.power(a, a)

array([[[  27.        ,   31.22925918],
        [  36.17701421,   41.97223378],
        [  48.76807468,   56.74658605],
        [  66.1243574 ,   77.15930535],
        [  90.15883438,  105.48965781]],

       [[ 123.58962517,  144.98197694],
        [ 170.29253735,  200.27046614],
        [ 235.81332436,  277.99737306],
        [ 328.11422348,  387.71520206],
        [ 458.6650923 ,  543.20728087]],

       [[ 644.04278334,  764.42617287],
        [ 908.28210718, 1080.34697339],
        [1286.34118122, 1533.17887681],
        [1829.22337451, 2184.59847887],
        [2611.56817461, 3125.        ]]])

In [45]:
np.divmod(arr, 5)

(array([[0, 0, 0],
        [0, 0, 1]]),
 array([[0, 1, 2],
        [3, 4, 0]]))

In [46]:
np.sign(arr)

array([[0, 1, 1],
       [1, 1, 1]])

In [47]:
np.log(2)

np.float64(0.6931471805599453)

In [48]:
np.log2(2)

np.float64(1.0)

In [51]:
truth=np.equal(arr, arr)
falsy = np.less(arr, arr)

In [53]:
np.logical_or(truth, falsy)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [54]:
1.2

1.2

In [58]:
np.inf

inf

In [56]:
np.nan

nan

In [72]:
np.trunc(np.array(['INF', 'inf', 'nan', 7.65656], dtype=np.float64))

array([inf, inf, nan,  7.])

In [73]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
view copy

In [ ]:

view
shallow copy
deep copy

In [75]:
view = arr

In [77]:
view[0,0] = 4

In [78]:
arr

array([[4, 1, 2],
       [3, 4, 5]])

In [104]:
shallow = arr.copy()

In [105]:
shallow[0] = 90

In [106]:
arr

array([[100, 100, 100],
       [  3,   4,   5]])

In [107]:
id(arr)

140631935156944

In [108]:
id(shallow)

140631935168848

In [94]:
id(arr), id(shallow)

(140631935156944, 140631935166928)

In [88]:
id(arr[0,0]), id(shallow[0,0])

(140631935815312, 140631935815312)

In [89]:
shallow

array([[90, 90, 90],
       [ 3,  4,  5]])

In [91]:
arr[0] = 100

In [92]:
shallow

array([[90, 90, 90],
       [ 3,  4,  5]])

In [93]:
arr

array([[100, 100, 100],
       [  3,   4,   5]])

In [101]:
id(arr[0,2])

140631935818320

In [102]:
id(shallow[0,2])

140631935817392

In [109]:
import copy

In [111]:
s = copy.copy(arr)

In [112]:
id(s), id(arr)

(140631935168944, 140631935156944)

In [113]:
id(s[0]), id(arr[0])

(140631935170576, 140631935170576)

In [123]:

id(s[0,0]),  id(arr[0,0])

(140631935821936, 140631935821936)

In [115]:
s[0,0] = 8


In [116]:
s

array([[  8, 100, 100],
       [  3,   4,   5]])

In [126]:
arr

array([[100, 100, 100],
       [  3,   4,   5]])

In [127]:
import copy

In [ ]:
copy.deepcopy()