In [2]:
import numpy as np

In [5]:
np.__version__

'2.4.2'

In [22]:
lst = list(range(500000))

In [23]:
%%timeit
# lst * 2

l = []
for i in lst:
    l.append(i*2)

52.3 ms ± 3.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
arr = np.array(lst) # create numpy array from list

In [25]:
arr

array([     0,      1,      2, ..., 499997, 499998, 499999],
      shape=(500000,))

In [26]:
%%timeit
arr*2

1.79 ms ± 22.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [31]:
np.array([1,2,3]) # int64
np.array([1,2,3.6]).dtype # upcasting

dtype('float64')

In [35]:
np.iinfo(np.int64)
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [38]:
np.array(['A', 'Baa', 'C55555'])

array(['A', 'Baa', 'C55555'], dtype='<U6')

In [40]:
np.array([True, False]).dtype

dtype('bool')

In [43]:
np.array([complex('2+3j')])

array([2.+3.j])

### 2D array

In [46]:
np.array([[1,3], [4,5]]) 

array([[1, 3],
       [4, 5]])

In [55]:
# range(start, stop, step) # AP 
arr = np.arange(0.0, 10.5, 0.5)

In [59]:
print(arr)
arr.shape # prints shape of array

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


(21,)

In [66]:
np.ones((2,4), dtype=np.int64) # create an array with all elemets 1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
np.array([3456565689048, 3498558745897344]), 

(array([   3456565689048, 3498558745897344]),)

In [76]:
np.array([3456565689048, 3498558745897344]).astype(np.int32)

array([ -882984232, -1354339968], dtype=int32)

In [79]:
np.array([127], dtype=np.int8)+1

array([-128], dtype=int8)

In [78]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [80]:
np.zeros((3,))

array([0., 0., 0.])