In [ ]:
## spliting

## spliting

In [ ]:
import numpy as np|

In [ ]:
arr = np.arange(0,20)

In [ ]:
arr.shape

(20,)

In [ ]:
np.split(arr, 3)

ValueError: array split does not result in an equal division

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.split(arr, [3, 6, 15])

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [ ]:

np.array_split(arr, 3)

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19])]

In [ ]:
np.array_split(arr, [3])

[array([0, 1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [ ]:
a = arr.reshape(10, 2)

In [ ]:
np.split(a, [2,6],axis=1)

[array([[[[[ 0]],
 
          [[ 1]],
 
          [[ 2]],
 
          [[ 3]],
 
          [[ 4]],
 
          [[ 5]],
 
          [[ 6]],
 
          [[ 7]],
 
          [[ 8]],
 
          [[ 9]]],
 
 
         [[[10]],
 
          [[11]],
 
          [[12]],
 
          [[13]],
 
          [[14]],
 
          [[15]],
 
          [[16]],
 
          [[17]],
 
          [[18]],
 
          [[19]]]]]),
 array([], shape=(1, 0, 10, 1, 1), dtype=int64),
 array([], shape=(1, 0, 10, 1, 1), dtype=int64)]

In [ ]:
# reshape, resize
arr.reshape(-1, 4) # error # -1 dim unknown

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# 10,2
# 2,10
# 1,20
# 20, 1
# 5,4
# 4,5

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.resize(5,4)

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

(2, 3)

In [ ]:
b = arr.reshape(5,4)

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
c = arr.resize(4,5)

In [ ]:
print(c)

None


In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
b.base is arr

True

In [ ]:
id(arr), id(b)

(132761718798448, 132761718797296)

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr.reshape(4,5, order='F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
# squeeze
a = arr.reshape(1, 2, 10, 1, 1)

In [ ]:
a.shape

(1, 2, 10, 1, 1)

In [ ]:
a

array([[[[[ 0]],

         [[ 1]],

         [[ 2]],

         [[ 3]],

         [[ 4]],

         [[ 5]],

         [[ 6]],

         [[ 7]],

         [[ 8]],

         [[ 9]]],


        [[[10]],

         [[11]],

         [[12]],

         [[13]],

         [[14]],

         [[15]],

         [[16]],

         [[17]],

         [[18]],

         [[19]]]]])

In [ ]:
a.squeeze().shape

(2, 10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr[(arr > 10) & (arr%2==0)]

array([12, 14, 16, 18])

In [ ]:
(arr > 10) &( arr%2==0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False,  True, False,
        True, False])

In [ ]:
c = np.where(((arr > 10) &( arr%2==0)), "True", "False")

In [ ]:
# np.where(condition, value_if_true, value_if_false)

In [ ]:
c

array(['False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'True', 'False', 'True', 'False', 'True', 'False'], dtype='<U5')

In [ ]:
arr.itemsize # size in bytes

8

In [ ]:
arr.astype(np.int16).itemsize

2

In [ ]:
np.random.rand(3,4)

array([[0.41038292, 0.75555114, 0.22879817, 0.07697991],
       [0.28975145, 0.16122129, 0.92969765, 0.80812038],
       [0.63340376, 0.87146059, 0.80367208, 0.18657006]])

In [ ]:
np.random.randn(4,3).std() # std dev close to 1 and mean close to 0

np.float64(1.0207728616197034)

In [ ]:
np.random.seed(42)


array([[8, 6, 8],
       [8, 6, 6],
       [8, 7, 8],
       [8, 8, 8]])

In [ ]:
np.random.seed(42)
np.random.randint(6, 9, (4,3))

array([[8, 6, 8],
       [8, 6, 6],
       [8, 7, 8],
       [8, 8, 8]])