In [1]:
import numpy as np

In [2]:
# sum, mean, median, 

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
np.sum(arr)

np.int64(6)

In [6]:
np.mean(arr)

np.float64(2.0)

In [7]:
np.median(arr)

np.float64(2.0)

In [8]:
np.std(arr)

np.float64(0.816496580927726)

In [9]:
np.var(arr)

np.float64(0.6666666666666666)

In [10]:
np.prod(arr)

np.int64(6)

In [11]:
arr.sum()

np.int64(6)

In [12]:
arr.mean()

np.float64(2.0)

In [13]:
arr = np.array([[1,2,3], [6,7,0]])

In [14]:
arr

array([[1, 2, 3],
       [6, 7, 0]])

In [15]:
np.sum(arr, axis=1)

array([ 6, 13])

In [16]:
np.mean(arr, axis=1)

array([2.        , 4.33333333])

In [17]:
np.std(arr, axis=0)

array([2.5, 2.5, 1.5])

In [18]:
np.var(arr, axis=0)

array([6.25, 6.25, 2.25])

In [19]:
# concat, stacking

In [20]:
arr

array([[1, 2, 3],
       [6, 7, 0]])

In [21]:
arr2 = np.arange(0, 6).reshape(2,3)

In [22]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
np.concatenate([arr, arr2])

array([[1, 2, 3],
       [6, 7, 0],
       [0, 1, 2],
       [3, 4, 5]])

In [24]:
# stacking

In [25]:
np.vstack([arr, arr2])

array([[1, 2, 3],
       [6, 7, 0],
       [0, 1, 2],
       [3, 4, 5]])

In [26]:
np.hstack([arr, arr2])

array([[1, 2, 3, 0, 1, 2],
       [6, 7, 0, 3, 4, 5]])

## spliting an array
### np.array_split, np.split

- sum
- mean
- prod
- std
- var


In [27]:
def func(a, b, axis=None):
    # print(np.sum(a, axis=axis))
    print(np.concatenate([a,b]))
    print(np.stack([a,b], axis=1))

In [28]:
func(np.array([1,2,3]), np.array([6,7, 8]))

[1 2 3 6 7 8]
[[1 6]
 [2 7]
 [3 8]]


In [29]:
arr * 3

array([[ 3,  6,  9],
       [18, 21,  0]])

In [30]:
arr

array([[1, 2, 3],
       [6, 7, 0]])

In [31]:
3

3

In [32]:
arr * 3

array([[ 3,  6,  9],
       [18, 21,  0]])

In [33]:
# broadcasting

In [34]:
arr

array([[1, 2, 3],
       [6, 7, 0]])

In [35]:
a = arr.copy() 

In [36]:
a[:] = 3

In [37]:
arr*a

array([[ 3,  6,  9],
       [18, 21,  0]])

In [38]:
arr  * np.array([[2,3, 7]])

array([[ 2,  6, 21],
       [12, 21,  0]])

In [39]:
arr

array([[1, 2, 3],
       [6, 7, 0]])

In [40]:
np.array([[2,3, 7]]).shape

(1, 3)

In [41]:
np.array([[2], [3]]).shape

(2, 1)

In [42]:
arr.shape

(2, 3)

In [43]:
arr + np.array([2, 3])

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
arr (40, 6)